"""
backend/app/report_generator.py

Generates a downloadable PDF screening report from a saved screening record.
Uses fpdf2 — a lightweight, pure-Python PDF library (no heavy native
dependencies), chosen deliberately for compatibility with lower-spec machines.
"""

from fpdf import FPDF
from datetime import datetime
from typing import Dict, Any
from io import BytesIO

# The built-in "Helvetica" PDF font only supports Latin-1 characters.
# Our KB content uses typographic punctuation (em-dashes, curly quotes,
# bullets) that Latin-1 doesn't include — sanitize before rendering rather
# than bundling extra Unicode font files (keeps the app lightweight).
_UNICODE_REPLACEMENTS = {
    "\u2014": "-",   # em dash —
    "\u2013": "-",   # en dash –
    "\u2018": "'",   # left single quote '
    "\u2019": "'",   # right single quote '
    "\u201c": '"',   # left double quote "
    "\u201d": '"',   # right double quote "
    "\u2022": "-",   # bullet •
    "\u2026": "...", # ellipsis …
    "\u00b0": " deg",  # degree sign ° (used in temperatures like 103°F)
}


def _sanitize(text: str) -> str:
    if not text:
        return ""
    for bad, good in _UNICODE_REPLACEMENTS.items():
        text = text.replace(bad, good)
    # final safety net: strip anything else outside Latin-1 rather than crash
    return text.encode("latin-1", errors="replace").decode("latin-1")


class ClariMedReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(20, 38, 58)  # deep clinical navy
        self.cell(0, 10, "ClariMed AI - Screening Report", ln=True)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, "AI-assisted preliminary screening - not a medical diagnosis.", ln=True)
        self.ln(4)
        self.set_draw_color(220, 227, 224)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(47, 111, 98)  # teal accent
        self.cell(0, 8, title, ln=True)
        self.set_text_color(20, 20, 20)

    def body_text(self, text: str, size: int = 10):
        self.set_font("Helvetica", "", size)
        self.multi_cell(0, 5.5, _sanitize(text))
        self.ln(1)


def generate_report_pdf(screening: Dict[str, Any]) -> bytes:
    """
    screening: a row dict as returned by ai.database.get_screening_by_id()
    (already has result_json/guidance as raw JSON/text strings).
    """
    import json

    result = json.loads(screening["result_json"]) if isinstance(screening["result_json"], str) else screening["result_json"]
    symptoms = json.loads(screening["symptoms_json"]) if isinstance(screening["symptoms_json"], str) else screening["symptoms_json"]
    guidance = screening.get("guidance") or ""

    pdf = ClariMedReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # --- Patient section ---
    pdf.section_title("Patient")
    pdf.body_text(
        f"Name: {screening.get('patient_name') or 'Not provided'}\n"
        f"Email: {screening.get('patient_email') or 'Not provided'}\n"
        f"Report generated: {datetime.utcnow().strftime('%d %b %Y, %H:%M UTC')}"
    )
    pdf.ln(2)

    # --- Screening summary ---
    pdf.section_title("Screening Summary")
    top = result.get("top")
    if top:
        pdf.body_text(
            f"Body part: {screening.get('body_part', '').title()}\n"
            f"Top result: {top['name']} ({top['pct']}% - {top.get('confidence_tier', '')})\n"
            f"Risk level: {result.get('risk_level', '').upper()}\n"
            f"Recommended specialist: {top.get('specialist', 'N/A')}\n"
            f"Symptoms reported: {', '.join(symptoms) if symptoms else 'None'}"
        )
    else:
        pdf.body_text(
            f"Body part: {screening.get('body_part', '').title()}\n"
            "Result: Outside current knowledge base coverage — see guidance below.\n"
            f"Symptoms reported: {', '.join(symptoms) if symptoms else 'None'}"
        )
    pdf.ln(2)

    # --- Differential ---
    if result.get("candidates"):
        pdf.section_title("Differential (Top Candidates)")
        for c in result["candidates"]:
            pdf.body_text(f"- {c['name']}: {c['pct']}% ({c.get('confidence_tier', '')})", size=10)
        pdf.ln(2)

    # --- Guidance (from knowledge base / RAG) ---
    pdf.section_title("Medical Guidance")
    clean_guidance = guidance.replace("###", "").replace("**", "").replace("*This", "This")
    pdf.body_text(clean_guidance, size=9.5)

    # --- Footer disclaimer ---
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.multi_cell(
        0, 4,
        _sanitize(
            "Generated by ClariMed AI (on-device preliminary screening). This is not a medical "
            "diagnosis. Please consult a licensed healthcare professional to confirm this result."
        )
    )

    buf = BytesIO()
    pdf.output(buf)
    return buf.getvalue()